### ISSUE TITLE
Tank name issue?

### ISSUE THREAD

**Issue by jthack** [huangyz0918/TankLogo#3]
I'm not sure if this a bug in the name or the logic, but when the red tank wins, the pop up says that the blue tank won:
![image](https://user-images.githubusercontent.com/2989856/47165655-6e435a00-d2c8-11e8-8da5-cdacbbe3cc14.png)

**Comment by huangyz0918** [comment]
Before creating a tank, you should set a name for it through the **TankName** box. This case means that you set the same name to both red and blue tank.
