### ISSUE TITLE
Graph issues

### ISSUE THREAD

**Issue by jthack** [huangyz0918/TankLogo#4]
The color of the legend in the graph changes over time even though it has the "blue tank" label, it starts as red, turns blue, and then turns back to red again:
![bug](https://user-images.githubusercontent.com/2989856/47165947-1bb66d80-d2c9-11e8-8d9b-d3d8ebee5bff.gif)

**Comment by huangyz0918** [comment]
The same issue as #3 . You should change a name before creating another tank.
