### ISSUE TITLE
Winner pop-up error

### ISSUE THREAD

**Issue by jthack** [huangyz0918/TankLogo#5]
If the blue tank (in the lower left) wins, the popup does not display the custom name set in the lower right. It just says "blue tank" as the name (which, due to issue #3) means that the popup literally always says "blue tank" won.

**Comment by jthack** [comment]
This is only true if you change the name AFTER setup. If you set the name before setup, it works fine. Also, @huangyz0918, does the order in which you create the tanks matter? I have been creating the blue tank first, but maybe creating the red tank first is the "proper" way to start.

**Comment by huangyz0918** [comment]
The naming progress should be something like this:
- typing a name for the blue tank(or the red one) in the **TankName** box.
- click **create tank** button.
- typing another name for the another tank in the **TankName** box.
- click **create tank** to create another one.

Hope this can help!

**Comment by jthack** [comment]
Okay yes, think makes way more sense now! Maybe add this to the documentation?

**Comment by huangyz0918** [comment]
@jthack good idea, or add another type box which related to the specific tank, would you like to do this stuff? Or I will update when I am free.

Thanks

**Comment by jthack** [comment]
I have never used netlogo, so i will let you do it! I AM working on my tank though ;)

**Comment by huangyz0918** [comment]
I have update the `README`, thanks for your reminder.
